### PR TITLE
Opcode search/highlight and Full FilePath in status Bar

### PR DESCRIPTION
**Pull request by fantoms**
I found it helpful to display the file path, when displaying multiple pcap files. This is also helpful to find a file after using the opcode search.

### CODE REVIEW

**Comment by fantoms** [comment]
* Enabled the search box.
* Added logic to replace the opcode highlight.
* Added a opcode highlight button.

**Comment by fantoms** [comment]
Lots of GUI enhancements and helper functions to speed up research:
- Can use Decimal or hex in the search box.
- Can now re-open a pcap as messages or without messages with new menu items.

**Comment by tfarley** [comment]
Sweet, this should be really helpful, thanks! Let me know if you're planning to make any further changes in this PR, otherwise LGTM and I'll merge.

**Comment by fantoms** [comment]
- Fixed a GUI warning, when you clicked on a column and a pcap file had not yet been loaded.
- Added the ability to use Enter in the Opcode search box, as well as clicking on the highlight button.

If the changes I've pushed since your last comment are good, them I am ready to merge.

**Pull request merged**
